var iconBasePath = '';
export default{
	'.doc':require('./static/img/word.png'),
	'.docx':require('./static/img/word.png'),
	'.xls':require('./static/img/excel.png'),
	'.xlsx':require('./static/img/excel.png'),
	'.ppt':require('./static/img/ppt.png'),
	'.pptx':require('./static/img/ppt.png'),
	'.pdf':require('./static/img/pdf.png'),
	'.txt':require('./static/img/txt.png'),
	'.jpg':require('./static/img/pic.png'),
	'.png':require('./static/img/pic.png'),
	'.gif':require('./static/img/pic.png'),
	'.bmp':require('./static/img/pic.png'),
	'.svg':require('./static/img/pic.png'),
	'.jpeg':require('./static/img/pic.png'),
	'.zip':require('./static/img/zip.png'),
	'.rar':require('./static/img/zip.png'),
	'.war':require('./static/img/zip.png'),
	'.jar':require('./static/img/zip.png'),
	'.7z':require('./static/img/zip.png'),
	'.unknow':require('./static/img/unknow.png'),
	'folder':require('./static/img/folder.png')
}
// export default{
// 	'.doc':import './static/img/word.png',
// 	'.docx':import './static/img/word.png',
// 	'.xls':import './static/img/excel.png',
// 	'.xlsx':import './static/img/excel.png',
// 	'.ppt':import './static/img/ppt.png',
// 	'.pptx':import './static/img/ppt.png',
// 	'.pdf':import './static/img/pdf.png',
// 	'.txt':import './static/img/txt.png',
// 	'.jpg':import './static/img/pic.png',
// 	'.png':import './static/img/pic.png',
// 	'.gif':import './static/img/pic.png',
// 	'.bmp':import './static/img/pic.png',
// 	'.svg':import './static/img/pic.png',
// 	'.jpeg':import './static/img/pic.png',
// 	'.zip':import './static/img/zip.png',
// 	'.rar':import './static/img/zip.png',
// 	'.war':import './static/img/zip.png',
// 	'.jar':import './static/img/zip.png',
// 	'.7z':import './static/img/zip.png',
// 	'.unknow':import './static/img/unknow.png',
// 	'folder':import './static/img/folder.png'
// }